#!/bin/bash
cp split-sample-vid/sample-vid022.png slides/
cp split-sample-vid/sample-vid023.png slides/
cp split-sample-vid/sample-vid025.png slides/
cp split-sample-vid/sample-vid026.png slides/
cp split-sample-vid/sample-vid038.png slides/
cp split-sample-vid/sample-vid047.png slides/
cp split-sample-vid/sample-vid052.png slides/
cp split-sample-vid/sample-vid072.png slides/
cp split-sample-vid/sample-vid079.png slides/
cp split-sample-vid/sample-vid108.png slides/
cp split-sample-vid/sample-vid116.png slides/
cp split-sample-vid/sample-vid127.png slides/
cp split-sample-vid/sample-vid142.png slides/
cp split-sample-vid/sample-vid170.png slides/
cp split-sample-vid/sample-vid175.png slides/
cp split-sample-vid/sample-vid176.png slides/
cp split-sample-vid/sample-vid177.png slides/
cp split-sample-vid/sample-vid211.png slides/
cp split-sample-vid/sample-vid217.png slides/
cp split-sample-vid/sample-vid222.png slides/
cp split-sample-vid/sample-vid239.png slides/
cp split-sample-vid/sample-vid241.png slides/
cp split-sample-vid/sample-vid253.png slides/
cp split-sample-vid/sample-vid260.png slides/
cp split-sample-vid/sample-vid264.png slides/
cp split-sample-vid/sample-vid297.png slides/
cp split-sample-vid/sample-vid303.png slides/
cp split-sample-vid/sample-vid310.png slides/
cp split-sample-vid/sample-vid321.png slides/
cp split-sample-vid/sample-vid342.png slides/
cp split-sample-vid/sample-vid344.png slides/
cp split-sample-vid/sample-vid351.png slides/
cp split-sample-vid/sample-vid379.png slides/
cp split-sample-vid/sample-vid385.png slides/
cp split-sample-vid/sample-vid386.png slides/
cp split-sample-vid/sample-vid387.png slides/
cp split-sample-vid/sample-vid394.png slides/
cp split-sample-vid/sample-vid412.png slides/
cp split-sample-vid/sample-vid419.png slides/
cp split-sample-vid/sample-vid421.png slides/
cp split-sample-vid/sample-vid444.png slides/
cp split-sample-vid/sample-vid454.png slides/
cp split-sample-vid/sample-vid460.png slides/
cp split-sample-vid/sample-vid466.png slides/
cp split-sample-vid/sample-vid468.png slides/
cp split-sample-vid/sample-vid490.png slides/
cp split-sample-vid/sample-vid492.png slides/
cp split-sample-vid/sample-vid495.png slides/
cp split-sample-vid/sample-vid505.png slides/
cp split-sample-vid/sample-vid508.png slides/
cp split-sample-vid/sample-vid510.png slides/
cp split-sample-vid/sample-vid516.png slides/
cp split-sample-vid/sample-vid520.png slides/
cp split-sample-vid/sample-vid542.png slides/
cp split-sample-vid/sample-vid585.png slides/
cp split-sample-vid/sample-vid586.png slides/
cp split-sample-vid/sample-vid589.png slides/
cp split-sample-vid/sample-vid591.png slides/
cp split-sample-vid/sample-vid601.png slides/
cp split-sample-vid/sample-vid616.png slides/
cp split-sample-vid/sample-vid618.png slides/
cp split-sample-vid/sample-vid623.png slides/
cp split-sample-vid/sample-vid631.png slides/
cp split-sample-vid/sample-vid643.png slides/
cp split-sample-vid/sample-vid653.png slides/
cp split-sample-vid/sample-vid705.png slides/
cp split-sample-vid/sample-vid708.png slides/
cp split-sample-vid/sample-vid711.png slides/
cp split-sample-vid/sample-vid719.png slides/
cp split-sample-vid/sample-vid739.png slides/
cp split-sample-vid/sample-vid750.png slides/
cp split-sample-vid/sample-vid766.png slides/
cp split-sample-vid/sample-vid773.png slides/
cp split-sample-vid/sample-vid775.png slides/
cp split-sample-vid/sample-vid780.png slides/
cp split-sample-vid/sample-vid781.png slides/
cp split-sample-vid/sample-vid802.png slides/
cp split-sample-vid/sample-vid805.png slides/
cp split-sample-vid/sample-vid806.png slides/
cp split-sample-vid/sample-vid812.png slides/
cp split-sample-vid/sample-vid816.png slides/
cp split-sample-vid/sample-vid837.png slides/
cp split-sample-vid/sample-vid842.png slides/
cp split-sample-vid/sample-vid851.png slides/
cp split-sample-vid/sample-vid852.png slides/
cp split-sample-vid/sample-vid867.png slides/
cp split-sample-vid/sample-vid871.png slides/
cp split-sample-vid/sample-vid891.png slides/
cp split-sample-vid/sample-vid892.png slides/
cp split-sample-vid/sample-vid894.png slides/
cp split-sample-vid/sample-vid899.png slides/
cp split-sample-vid/sample-vid911.png slides/
cp split-sample-vid/sample-vid916.png slides/
cp split-sample-vid/sample-vid926.png slides/
cp split-sample-vid/sample-vid976.png slides/