#!/bin/bash
cp tmp-ffmpeg-folder/out02192.png tmp-output-folder
cp tmp-ffmpeg-folder/out01211.png tmp-output-folder
cp tmp-ffmpeg-folder/out00387.png tmp-output-folder
cp tmp-ffmpeg-folder/out02620.png tmp-output-folder
cp tmp-ffmpeg-folder/out01121.png tmp-output-folder
cp tmp-ffmpeg-folder/out02599.png tmp-output-folder
cp tmp-ffmpeg-folder/out00024.png tmp-output-folder
cp tmp-ffmpeg-folder/out00771.png tmp-output-folder
cp tmp-ffmpeg-folder/out03169.png tmp-output-folder
cp tmp-ffmpeg-folder/out00239.png tmp-output-folder
cp tmp-ffmpeg-folder/out02379.png tmp-output-folder
cp tmp-ffmpeg-folder/out01018.png tmp-output-folder
cp tmp-ffmpeg-folder/out01250.png tmp-output-folder
cp tmp-ffmpeg-folder/out02768.png tmp-output-folder
cp tmp-ffmpeg-folder/out02257.png tmp-output-folder
cp tmp-ffmpeg-folder/out02338.png tmp-output-folder
cp tmp-ffmpeg-folder/out03447.png tmp-output-folder
cp tmp-ffmpeg-folder/out03612.png tmp-output-folder
cp tmp-ffmpeg-folder/out01146.png tmp-output-folder
cp tmp-ffmpeg-folder/out03561.png tmp-output-folder
cp tmp-ffmpeg-folder/out00788.png tmp-output-folder
cp tmp-ffmpeg-folder/out03313.png tmp-output-folder
cp tmp-ffmpeg-folder/out01643.png tmp-output-folder
cp tmp-ffmpeg-folder/out02913.png tmp-output-folder
cp tmp-ffmpeg-folder/out01867.png tmp-output-folder
cp tmp-ffmpeg-folder/out01737.png tmp-output-folder
cp tmp-ffmpeg-folder/out00714.png tmp-output-folder
cp tmp-ffmpeg-folder/out00832.png tmp-output-folder
cp tmp-ffmpeg-folder/out03191.png tmp-output-folder
cp tmp-ffmpeg-folder/out01799.png tmp-output-folder
cp tmp-ffmpeg-folder/out01528.png tmp-output-folder
cp tmp-ffmpeg-folder/out02168.png tmp-output-folder
cp tmp-ffmpeg-folder/out03527.png tmp-output-folder
cp tmp-ffmpeg-folder/out00658.png tmp-output-folder
cp tmp-ffmpeg-folder/out02645.png tmp-output-folder
cp tmp-ffmpeg-folder/out01853.png tmp-output-folder
cp tmp-ffmpeg-folder/out00315.png tmp-output-folder
cp tmp-ffmpeg-folder/out01318.png tmp-output-folder
cp tmp-ffmpeg-folder/out01792.png tmp-output-folder
cp tmp-ffmpeg-folder/out02624.png tmp-output-folder
cp tmp-ffmpeg-folder/out00216.png tmp-output-folder
cp tmp-ffmpeg-folder/out01082.png tmp-output-folder
cp tmp-ffmpeg-folder/out01130.png tmp-output-folder
cp tmp-ffmpeg-folder/out03478.png tmp-output-folder
cp tmp-ffmpeg-folder/out01405.png tmp-output-folder
cp tmp-ffmpeg-folder/out03605.png tmp-output-folder
cp tmp-ffmpeg-folder/out00508.png tmp-output-folder
cp tmp-ffmpeg-folder/out02706.png tmp-output-folder
cp tmp-ffmpeg-folder/out00903.png tmp-output-folder
cp tmp-ffmpeg-folder/out02665.png tmp-output-folder
cp tmp-ffmpeg-folder/out02518.png tmp-output-folder
cp tmp-ffmpeg-folder/out00152.png tmp-output-folder
cp tmp-ffmpeg-folder/out02027.png tmp-output-folder
cp tmp-ffmpeg-folder/out00636.png tmp-output-folder
cp tmp-ffmpeg-folder/out01190.png tmp-output-folder
cp tmp-ffmpeg-folder/out00364.png tmp-output-folder
cp tmp-ffmpeg-folder/out01927.png tmp-output-folder
cp tmp-ffmpeg-folder/out03208.png tmp-output-folder
cp tmp-ffmpeg-folder/out00812.png tmp-output-folder
cp tmp-ffmpeg-folder/out01049.png tmp-output-folder
cp tmp-ffmpeg-folder/out01601.png tmp-output-folder
cp tmp-ffmpeg-folder/out00819.png tmp-output-folder
cp tmp-ffmpeg-folder/out01615.png tmp-output-folder
cp tmp-ffmpeg-folder/out00595.png tmp-output-folder
cp tmp-ffmpeg-folder/out00276.png tmp-output-folder
cp tmp-ffmpeg-folder/out02466.png tmp-output-folder
cp tmp-ffmpeg-folder/out02685.png tmp-output-folder
cp tmp-ffmpeg-folder/out01823.png tmp-output-folder
cp tmp-ffmpeg-folder/out02730.png tmp-output-folder
cp tmp-ffmpeg-folder/out02386.png tmp-output-folder
cp tmp-ffmpeg-folder/out02405.png tmp-output-folder
cp tmp-ffmpeg-folder/out00154.png tmp-output-folder
cp tmp-ffmpeg-folder/out01650.png tmp-output-folder
cp tmp-ffmpeg-folder/out01664.png tmp-output-folder
cp tmp-ffmpeg-folder/out01164.png tmp-output-folder
cp tmp-ffmpeg-folder/out02135.png tmp-output-folder
cp tmp-ffmpeg-folder/out01030.png tmp-output-folder
cp tmp-ffmpeg-folder/out01762.png tmp-output-folder
cp tmp-ffmpeg-folder/out01768.png tmp-output-folder
cp tmp-ffmpeg-folder/out03256.png tmp-output-folder
cp tmp-ffmpeg-folder/out01560.png tmp-output-folder
cp tmp-ffmpeg-folder/out02641.png tmp-output-folder
cp tmp-ffmpeg-folder/out00849.png tmp-output-folder
cp tmp-ffmpeg-folder/out00327.png tmp-output-folder
cp tmp-ffmpeg-folder/out00961.png tmp-output-folder
cp tmp-ffmpeg-folder/out03262.png tmp-output-folder
cp tmp-ffmpeg-folder/out00169.png tmp-output-folder
cp tmp-ffmpeg-folder/out03421.png tmp-output-folder
cp tmp-ffmpeg-folder/out03080.png tmp-output-folder
cp tmp-ffmpeg-folder/out02529.png tmp-output-folder
cp tmp-ffmpeg-folder/out02207.png tmp-output-folder
cp tmp-ffmpeg-folder/out03133.png tmp-output-folder
cp tmp-ffmpeg-folder/out02902.png tmp-output-folder
cp tmp-ffmpeg-folder/out03098.png tmp-output-folder
cp tmp-ffmpeg-folder/out00186.png tmp-output-folder
cp tmp-ffmpeg-folder/out00489.png tmp-output-folder
cp tmp-ffmpeg-folder/out02364.png tmp-output-folder
cp tmp-ffmpeg-folder/out00717.png tmp-output-folder
cp tmp-ffmpeg-folder/out01223.png tmp-output-folder
cp tmp-ffmpeg-folder/out00194.png tmp-output-folder
cp tmp-ffmpeg-folder/out00480.png tmp-output-folder
cp tmp-ffmpeg-folder/out03104.png tmp-output-folder
cp tmp-ffmpeg-folder/out00282.png tmp-output-folder
cp tmp-ffmpeg-folder/out00271.png tmp-output-folder
cp tmp-ffmpeg-folder/out01892.png tmp-output-folder
cp tmp-ffmpeg-folder/out01471.png tmp-output-folder
cp tmp-ffmpeg-folder/out02750.png tmp-output-folder
cp tmp-ffmpeg-folder/out01080.png tmp-output-folder
cp tmp-ffmpeg-folder/out03301.png tmp-output-folder
cp tmp-ffmpeg-folder/out03594.png tmp-output-folder
cp tmp-ffmpeg-folder/out00331.png tmp-output-folder
cp tmp-ffmpeg-folder/out00577.png tmp-output-folder
cp tmp-ffmpeg-folder/out01230.png tmp-output-folder
cp tmp-ffmpeg-folder/out02592.png tmp-output-folder
cp tmp-ffmpeg-folder/out01455.png tmp-output-folder
cp tmp-ffmpeg-folder/out02767.png tmp-output-folder
cp tmp-ffmpeg-folder/out03601.png tmp-output-folder
cp tmp-ffmpeg-folder/out00321.png tmp-output-folder
cp tmp-ffmpeg-folder/out01781.png tmp-output-folder
cp tmp-ffmpeg-folder/out03126.png tmp-output-folder
cp tmp-ffmpeg-folder/out02033.png tmp-output-folder
cp tmp-ffmpeg-folder/out00589.png tmp-output-folder
cp tmp-ffmpeg-folder/out00617.png tmp-output-folder
cp tmp-ffmpeg-folder/out03392.png tmp-output-folder
cp tmp-ffmpeg-folder/out02519.png tmp-output-folder
cp tmp-ffmpeg-folder/out01637.png tmp-output-folder
cp tmp-ffmpeg-folder/out03486.png tmp-output-folder
cp tmp-ffmpeg-folder/out01383.png tmp-output-folder
cp tmp-ffmpeg-folder/out03401.png tmp-output-folder
cp tmp-ffmpeg-folder/out00320.png tmp-output-folder
cp tmp-ffmpeg-folder/out01340.png tmp-output-folder
cp tmp-ffmpeg-folder/out02800.png tmp-output-folder
cp tmp-ffmpeg-folder/out00361.png tmp-output-folder
cp tmp-ffmpeg-folder/out02948.png tmp-output-folder
cp tmp-ffmpeg-folder/out02090.png tmp-output-folder
cp tmp-ffmpeg-folder/out00850.png tmp-output-folder
cp tmp-ffmpeg-folder/out00605.png tmp-output-folder
cp tmp-ffmpeg-folder/out00953.png tmp-output-folder
cp tmp-ffmpeg-folder/out01168.png tmp-output-folder
cp tmp-ffmpeg-folder/out00221.png tmp-output-folder
cp tmp-ffmpeg-folder/out02692.png tmp-output-folder
cp tmp-ffmpeg-folder/out01435.png tmp-output-folder
cp tmp-ffmpeg-folder/out01394.png tmp-output-folder
cp tmp-ffmpeg-folder/out03168.png tmp-output-folder
cp tmp-ffmpeg-folder/out01463.png tmp-output-folder
cp tmp-ffmpeg-folder/out03296.png tmp-output-folder
cp tmp-ffmpeg-folder/out02219.png tmp-output-folder
cp tmp-ffmpeg-folder/out00749.png tmp-output-folder
cp tmp-ffmpeg-folder/out00385.png tmp-output-folder
cp tmp-ffmpeg-folder/out02138.png tmp-output-folder
cp tmp-ffmpeg-folder/out01255.png tmp-output-folder
cp tmp-ffmpeg-folder/out00633.png tmp-output-folder
cp tmp-ffmpeg-folder/out00995.png tmp-output-folder
cp tmp-ffmpeg-folder/out02566.png tmp-output-folder
cp tmp-ffmpeg-folder/out00657.png tmp-output-folder
cp tmp-ffmpeg-folder/out01819.png tmp-output-folder
cp tmp-ffmpeg-folder/out00373.png tmp-output-folder
cp tmp-ffmpeg-folder/out01292.png tmp-output-folder
cp tmp-ffmpeg-folder/out03588.png tmp-output-folder
cp tmp-ffmpeg-folder/out02919.png tmp-output-folder
cp tmp-ffmpeg-folder/out02929.png tmp-output-folder
cp tmp-ffmpeg-folder/out03467.png tmp-output-folder
cp tmp-ffmpeg-folder/out02041.png tmp-output-folder
cp tmp-ffmpeg-folder/out01814.png tmp-output-folder
cp tmp-ffmpeg-folder/out03419.png tmp-output-folder
cp tmp-ffmpeg-folder/out02344.png tmp-output-folder
cp tmp-ffmpeg-folder/out00534.png tmp-output-folder
cp tmp-ffmpeg-folder/out02950.png tmp-output-folder
cp tmp-ffmpeg-folder/out02797.png tmp-output-folder
