#!/bin/bash
cp tmp-ffmpeg-folder/out00003.png tmp-output-folder
cp tmp-ffmpeg-folder/out00025.png tmp-output-folder
cp tmp-ffmpeg-folder/out00050.png tmp-output-folder
cp tmp-ffmpeg-folder/out00067.png tmp-output-folder
cp tmp-ffmpeg-folder/out00082.png tmp-output-folder
cp tmp-ffmpeg-folder/out00132.png tmp-output-folder
cp tmp-ffmpeg-folder/out00133.png tmp-output-folder
cp tmp-ffmpeg-folder/out00136.png tmp-output-folder
cp tmp-ffmpeg-folder/out00164.png tmp-output-folder
cp tmp-ffmpeg-folder/out00182.png tmp-output-folder
cp tmp-ffmpeg-folder/out00186.png tmp-output-folder
cp tmp-ffmpeg-folder/out00212.png tmp-output-folder
cp tmp-ffmpeg-folder/out00235.png tmp-output-folder
cp tmp-ffmpeg-folder/out00249.png tmp-output-folder
cp tmp-ffmpeg-folder/out00261.png tmp-output-folder
cp tmp-ffmpeg-folder/out00291.png tmp-output-folder
cp tmp-ffmpeg-folder/out00303.png tmp-output-folder
cp tmp-ffmpeg-folder/out00321.png tmp-output-folder
cp tmp-ffmpeg-folder/out00323.png tmp-output-folder
cp tmp-ffmpeg-folder/out00333.png tmp-output-folder
cp tmp-ffmpeg-folder/out00363.png tmp-output-folder
cp tmp-ffmpeg-folder/out00364.png tmp-output-folder
cp tmp-ffmpeg-folder/out00375.png tmp-output-folder
cp tmp-ffmpeg-folder/out00396.png tmp-output-folder
cp tmp-ffmpeg-folder/out00416.png tmp-output-folder
cp tmp-ffmpeg-folder/out00439.png tmp-output-folder
cp tmp-ffmpeg-folder/out00473.png tmp-output-folder
cp tmp-ffmpeg-folder/out00482.png tmp-output-folder
cp tmp-ffmpeg-folder/out00503.png tmp-output-folder
